/**
 * ParaMembrosPage.jsx
 * "For Members" — what club members see and can do.
 * Public page, no auth required.
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import ClubeHeader from '../components/ClubeHeader.jsx';
import ClubeFooter from '../components/ClubeFooter.jsx';
import { CLUBE_COLORS, CLUBE_FONTS } from '../styles/index.js';

// ─── Bilingual content ──────────────────────────────────────────────────────────

const HERO = {
  pt: {
    label: 'PARA COTISTAS',
    headline: 'Acompanhe seu clube com clareza.',
    subline: 'Performance, NAV, relatórios e governança — tudo que o cotista precisa para acompanhar seu investimento coletivo.',
  },
  en: {
    label: 'FOR MEMBERS',
    headline: 'Follow your club with clarity.',
    subline: 'Performance, NAV, reports, and governance — everything a member needs to track their collective investment.',
  },
};

const FEATURES = {
  pt: [
    {
      icon: '📈',
      title: 'Dashboard do clube',
      desc: 'Veja o patrimônio líquido, valor da sua cota, rentabilidade acumulada e comparação com CDI e IBOVESPA em um único painel.',
    },
    {
      icon: '📊',
      title: 'Histórico de performance',
      desc: 'Acompanhe a evolução do clube mês a mês. Gráficos de NAV, rentabilidade e comparação com o benchmark escolhido pelo gestor.',
    },
    {
      icon: '📄',
      title: 'Relatórios mensais',
      desc: 'Acesse os relatórios mensais gerados pelo gestor com análise de mercado, performance do período e comentários em português.',
    },
    {
      icon: '🗳️',
      title: 'Assembleias',
      desc: 'Receba convocações, vote em pautas e acesse as atas de todas as assembleias do clube. Governança transparente e participativa.',
    },
    {
      icon: '📁',
      title: 'Documentos legais',
      desc: 'Estatuto do clube, extratos de movimentação, comprovantes de aporte e documentos regulatórios sempre disponíveis.',
    },
  ],
  en: [
    {
      icon: '📈',
      title: 'Club dashboard',
      desc: 'See net asset value, your quota value, accumulated returns, and comparison with CDI and IBOVESPA in a single panel.',
    },
    {
      icon: '📊',
      title: 'Performance history',
      desc: 'Track the club\'s evolution month by month. NAV charts, returns, and comparison with the benchmark chosen by the manager.',
    },
    {
      icon: '📄',
      title: 'Monthly reports',
      desc: 'Access monthly reports generated by the manager with market analysis, period performance, and commentary in Portuguese.',
    },
    {
      icon: '🗳️',
      title: 'Assemblies',
      desc: 'Receive notices, vote on agenda items, and access minutes from all club assemblies. Transparent and participatory governance.',
    },
    {
      icon: '📁',
      title: 'Legal documents',
      desc: 'Club bylaws, transaction statements, contribution receipts, and regulatory documents always available.',
    },
  ],
};

const JOURNEY = {
  pt: {
    label: 'SUA JORNADA COMO COTISTA',
    headline: 'Do convite ao acompanhamento.',
    steps: [
      {
        number: '01',
        title: 'Convite do gestor',
        desc: 'O gestor do clube adiciona você como cotista na plataforma e registra seu aporte inicial.',
      },
      {
        number: '02',
        title: 'Acesso ao Clube GMT',
        desc: 'Você cria sua conta no Clube GMT e acessa o dashboard do clube com todos os dados do seu investimento.',
      },
      {
        number: '03',
        title: 'Acompanhamento contínuo',
        desc: 'Acompanhe a performance do clube semanalmente, acesse relatórios mensais e participe das assembleias.',
      },
      {
        number: '04',
        title: 'Transparência total',
        desc: 'Todos os documentos, movimentações e decisões do clube ficam registrados e acessíveis a qualquer momento.',
      },
    ],
  },
  en: {
    label: 'YOUR JOURNEY AS A MEMBER',
    headline: 'From invitation to ongoing tracking.',
    steps: [
      {
        number: '01',
        title: 'Manager invitation',
        desc: 'The club manager adds you as a member on the platform and records your initial contribution.',
      },
      {
        number: '02',
        title: 'Access to Clube GMT',
        desc: 'You create your account on Clube GMT and access the club dashboard with all your investment data.',
      },
      {
        number: '03',
        title: 'Ongoing tracking',
        desc: 'Follow the club\'s performance weekly, access monthly reports, and participate in assemblies.',
      },
      {
        number: '04',
        title: 'Full transparency',
        desc: 'All documents, transactions, and club decisions are recorded and accessible at any time.',
      },
    ],
  },
};

const NOT_YOUR_JOB = {
  pt: {
    label: 'VOCÊ NÃO PRECISA SE PREOCUPAR COM',
    items: [
      'Cálculo de cotas e rentabilidade',
      'Compliance CVM e enquadramento',
      'Geração de relatórios',
      'Documentação regulatória',
      'Gestão de assembleias',
    ],
    note: 'Isso é trabalho do gestor. Você só acompanha.',
  },
  en: {
    label: 'YOU DON\'T NEED TO WORRY ABOUT',
    items: [
      'Quota and return calculations',
      'CVM compliance and rebalancing',
      'Report generation',
      'Regulatory documentation',
      'Assembly management',
    ],
    note: 'That\'s the manager\'s job. You just track.',
  },
};

const CTA = {
  pt: {
    headline: 'Já faz parte de um clube?',
    sub: 'Peça ao seu gestor para te adicionar no Clube GMT.',
    btn: 'Sou cotista, quero acesso',
    link: 'Falar com a equipe →',
  },
  en: {
    headline: 'Already part of a club?',
    sub: 'Ask your manager to add you to Clube GMT.',
    btn: 'I\'m a member, I want access',
    link: 'Talk to the team →',
  },
};

// ─── Component ──────────────────────────────────────────────────────────────────

export default function ParaMembrosPage() {
  const { i18n } = useTranslation();
  const [lang, setLang] = useState(i18n.language?.startsWith('en') ? 'en' : 'pt');
  const handleLangChange = (newLang) => {
    setLang(newLang);
    i18n.changeLanguage(newLang);
  };
  const navigate = useNavigate();

  const hero = HERO[lang] || HERO.pt;
  const features = FEATURES[lang] || FEATURES.pt;
  const journey = JOURNEY[lang] || JOURNEY.pt;
  const notYourJob = NOT_YOUR_JOB[lang] || NOT_YOUR_JOB.pt;
  const cta = CTA[lang] || CTA.pt;

  return (
    <div style={{
      minHeight: '100vh',
      background: CLUBE_COLORS.bg,
      color: CLUBE_COLORS.textPrimary,
      fontFamily: CLUBE_FONTS.sans,
      display: 'flex',
      flexDirection: 'column',
    }}>
      <ClubeHeader
        lang={lang}
        onLangChange={handleLangChange}
        onSignIn={() => navigate('/login')}
        onSignUp={() => navigate('/register')}
      />

      <div style={{ height: 56 }} />

      <main style={{ flex: 1 }}>

        {/* ── Hero ─────────────────────────────────────────────────────── */}
        <section style={{
          padding: '64px 40px 48px',
          textAlign: 'center',
          maxWidth: 760,
          margin: '0 auto',
        }}>
          <div style={{
            fontSize: 11,
            fontFamily: CLUBE_FONTS.mono,
            letterSpacing: '0.2em',
            textTransform: 'uppercase',
            color: CLUBE_COLORS.accent,
            marginBottom: 16,
          }}>
            {hero.label}
          </div>
          <h1 style={{
            fontFamily: "'Syne', sans-serif",
            fontSize: 'clamp(28px, 4.5vw, 40px)',
            fontWeight: 800,
            lineHeight: 1.15,
            color: 'white',
            margin: '0 0 20px',
          }}>
            {hero.headline}
          </h1>
          <p style={{
            fontSize: 18,
            color: 'rgba(255,255,255,0.55)',
            lineHeight: 1.6,
            maxWidth: 600,
            margin: '0 auto',
          }}>
            {hero.subline}
          </p>
        </section>

        {/* ── Section 1: Member dashboard features ─────────────────────── */}
        <section style={{
          padding: '48px 40px 64px',
          maxWidth: 1080,
          margin: '0 auto',
        }}>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
            gap: 16,
          }}>
            {features.map((f, i) => (
              <div
                key={i}
                style={{
                  background: CLUBE_COLORS.bgSurface,
                  border: '1px solid rgba(255,255,255,0.06)',
                  borderRadius: 12,
                  padding: '28px 24px',
                  transition: 'border-color 200ms',
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = CLUBE_COLORS.borderGold; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)'; }}
              >
                <div style={{ fontSize: 28, marginBottom: 16 }}>{f.icon}</div>
                <div style={{
                  fontSize: 15,
                  fontWeight: 600,
                  color: 'white',
                  marginBottom: 10,
                }}>
                  {f.title}
                </div>
                <div style={{
                  fontSize: 13,
                  color: 'rgba(255,255,255,0.5)',
                  lineHeight: 1.7,
                }}>
                  {f.desc}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Section 2: Member journey timeline ───────────────────────── */}
        <section style={{
          padding: '0 40px 64px',
          maxWidth: 680,
          margin: '0 auto',
        }}>
          <div style={{
            fontSize: 10,
            fontFamily: CLUBE_FONTS.mono,
            letterSpacing: '0.2em',
            textTransform: 'uppercase',
            color: CLUBE_COLORS.accent,
            marginBottom: 12,
            textAlign: 'center',
          }}>
            {journey.label}
          </div>
          <h2 style={{
            fontFamily: "'Syne', sans-serif",
            fontSize: 24,
            fontWeight: 700,
            color: 'white',
            margin: '0 0 32px',
            textAlign: 'center',
          }}>
            {journey.headline}
          </h2>

          {journey.steps.map((step, i) => (
            <div
              key={step.number}
              style={{
                display: 'flex',
                gap: 24,
                padding: '24px 0',
                borderBottom: i < journey.steps.length - 1
                  ? '1px solid rgba(255,255,255,0.04)'
                  : 'none',
                position: 'relative',
              }}
            >
              <div style={{
                width: 60,
                flexShrink: 0,
                position: 'relative',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
              }}>
                <span style={{
                  fontFamily: CLUBE_FONTS.mono,
                  fontSize: 32,
                  fontWeight: 800,
                  color: CLUBE_COLORS.accent,
                  lineHeight: 1,
                }}>
                  {step.number}
                </span>
                {i < journey.steps.length - 1 && (
                  <div style={{
                    position: 'absolute',
                    top: 40,
                    bottom: -24,
                    width: 2,
                    background: 'rgba(249,195,0,0.15)',
                  }} />
                )}
              </div>
              <div style={{ flex: 1, paddingTop: 4 }}>
                <div style={{
                  fontSize: 16,
                  fontWeight: 600,
                  color: 'white',
                  marginBottom: 8,
                }}>
                  {step.title}
                </div>
                <div style={{
                  fontSize: 14,
                  color: 'rgba(255,255,255,0.55)',
                  lineHeight: 1.7,
                }}>
                  {step.desc}
                </div>
              </div>
            </div>
          ))}
        </section>

        {/* ── Section 3: What members don't need to do ─────────────────── */}
        <section style={{
          padding: '0 40px 64px',
          display: 'flex',
          justifyContent: 'center',
        }}>
          <div style={{
            maxWidth: 560,
            width: '100%',
            background: 'rgba(249,195,0,0.04)',
            border: '1px solid rgba(249,195,0,0.15)',
            borderRadius: 12,
            padding: '36px 40px',
          }}>
            <div style={{
              fontSize: 10,
              fontFamily: CLUBE_FONTS.mono,
              letterSpacing: '0.2em',
              textTransform: 'uppercase',
              color: CLUBE_COLORS.accent,
              marginBottom: 20,
              textAlign: 'center',
            }}>
              {notYourJob.label}
            </div>
            {notYourJob.items.map((item, i) => (
              <div key={i} style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                fontSize: 14,
                color: CLUBE_COLORS.textPrimary,
                padding: '6px 0',
                borderBottom: i < notYourJob.items.length - 1
                  ? '1px solid rgba(255,255,255,0.04)'
                  : 'none',
              }}>
                <span style={{ color: CLUBE_COLORS.accent, fontSize: 12, flexShrink: 0 }}>✓</span>
                {item}
              </div>
            ))}
            <div style={{
              fontSize: 13,
              color: 'rgba(255,255,255,0.4)',
              fontStyle: 'italic',
              marginTop: 20,
              textAlign: 'center',
            }}>
              {notYourJob.note}
            </div>
          </div>
        </section>

        {/* ── Section 4: Final CTA ─────────────────────────────────────── */}
        <section style={{
          padding: '64px 40px',
          textAlign: 'center',
        }}>
          <h2 style={{
            fontFamily: "'Syne', sans-serif",
            fontSize: 28,
            fontWeight: 700,
            color: 'rgba(255,255,255,0.92)',
            margin: '0 0 12px',
          }}>
            {cta.headline}
          </h2>
          <p style={{
            fontSize: 14,
            fontWeight: 300,
            color: 'rgba(255,255,255,0.4)',
            maxWidth: 480,
            margin: '0 auto 32px',
            lineHeight: 1.6,
          }}>
            {cta.sub}
          </p>
          <button
            onClick={() => navigate('/login')}
            style={{
              background: CLUBE_COLORS.ctaBg,
              color: CLUBE_COLORS.ctaText,
              border: 'none',
              borderRadius: 8,
              padding: '11px 28px',
              fontSize: 14,
              fontWeight: 600,
              cursor: 'pointer',
              fontFamily: CLUBE_FONTS.sans,
              transition: 'background 0.15s',
              marginBottom: 16,
            }}
            onMouseEnter={e => { e.currentTarget.style.background = CLUBE_COLORS.ctaHover; }}
            onMouseLeave={e => { e.currentTarget.style.background = CLUBE_COLORS.ctaBg; }}
          >
            {cta.btn}
          </button>
          <div>
            <button
              onClick={() => { window.location.href = 'mailto:contato@gmt.app'; }}
              style={{
                background: 'transparent',
                border: 'none',
                cursor: 'pointer',
                fontSize: 13,
                color: CLUBE_COLORS.accentDim,
                fontFamily: CLUBE_FONTS.sans,
                transition: 'color 0.15s',
              }}
              onMouseEnter={e => { e.currentTarget.style.color = CLUBE_COLORS.accent; }}
              onMouseLeave={e => { e.currentTarget.style.color = CLUBE_COLORS.accentDim; }}
            >
              {cta.link}
            </button>
          </div>
        </section>

      </main>

      <ClubeFooter lang={lang} />
    </div>
  );
}
